##
## Welcome to Jekyll!
## ------------------
## This config file is meant for settings that affect your whole blog, values
## which you are expected to set up once and rarely edit after that. If you find
## yourself editing this file very often, consider using Jekyll's data files
## feature for the data you need to update frequently.
##
## For technical reasons, this file is *NOT* reloaded automatically when you use
## 'bundle exec jekyll serve'. If you change this file, please restart the server process.


##
## Site Settings
## -------------
## These are used to personalize your new site. If you look in the HTML files,
## you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
## You can create any custom variable you would like, and they will be accessible
## in the templates via {{ site.myvariable }}.

meta:
  title: Keenan Payne
  description: This is the home page of Keenan Payne, a freelance web developer. Learn how I can help you grow as a freelancer or help your business succeed on the web.
  link: "https://keenanpayne.com"


##
## Globals
## --------

globals:
  name: Keenan Payne


##
## Social Networks
## ---------------

social:
  - name: "Dribbble"
    url: "https://dribbble.com/keenanpayne"
  - name: "GitHub"
    url: "https://github.com/keenanpayne"
  - name: "Behance"
    url: "https://www.behance.net/keenanpayne"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/keenanpayne"
  - name: "CodePen"
    url: "https://codepen.io/keenanpayne/"


##
## Build Settings
## --------------

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - js/webp.js
  - src
  - new


##
## Defaults
## --------

defaults:
  -
    # Set default layout for all posts
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:title.html"
